### ISSUE TITLE
Null Pointer Exception from monsters

### ISSUE THREAD

**Issue by RyanGrieb** [rhin123/KingdomraidersServer#3]
Occurs when multiple players are in a dungeon. Maybe has to do with them leaving?

**Comment by RyanGrieb** [comment]
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at me.rhin.kingdomraiders.server.thread.UpdateThread.fastUpdate(UpdateThread.java:81)
	at me.rhin.kingdomraiders.server.thread.UpdateThread$2.run(UpdateThread.java:34)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RyanGrieb** [comment]
I only addressed this with monsters, players might trigger the exceptions as well.
